//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ParameterId { get; set; }
        public int TestId { get; set; }
        public string ParameterName { get; set; }
        public decimal RequiredValue { get; set; }
        public decimal MeasuredValue { get; set; }
    
        public virtual Test Tests { get; set; }
    }
}
